CREATE TABLE POPULATION1(
  Country TEXT,
  Population INTEGER,
  INTERNET_USER INTEGER,
  POPULATION_RATE TEXT,
  GROWTH TEXT
);

INSERT INTO POPULATION1(Country, Population, INTERNET_USER, POPULATION_RATE, GROWTH)VALUES
('United States', 335, 312, '93.1%', '1.8%'),
('Brazil', 217, 179, '82.5%', '2.3%'),
('Indonesia', 278, 210, '75.5%', '4.6%'),
('Bangladesh', 173, 76, '43.9%', '6.7%'),
('Nigeria', 225, 109, '48.4%', '5.9%'),
('Russia', 144, 122, '84.7%', '0.9%'),
('Japan', 125, 118, '94.4%', '0.5%'),
('Germany', 84, 79, '94.0%', '1.0%');

-- TESTING --
SELECT * FROM POPULATION1;
-- TESTED --

-- WHICH ARE THE THE UNIC POPULATION ?
SELECT DISTINCT(Population) AS UNIC_POPULATION FROM  POPULATION1;

-- HOW MANY UNICS ARE THERE?
SELECT COUNT(DISTINCT(Population)) AS COUNTER FROM POPULATION1;

-- GIVE ENTER IN OUTPUT?
SELECT 
"NAME: "||Country||CHAR(10)||"POPULATION: "||Population AS COUNTRY_VS_POPULATION
FROM POPULATION1;

-- WHICH COUNTRY HAS MAX POPULATION?
SELECT Country,MAX(Population) FROM POPULATION1;

-- WHICH COUNTRY HAS MINIMUM POPULATION?
SELECT Country, MIN(Population) FROM POPULATION1;

-- WHICH IS THE SUM OF POPULATION?
SELECT SUM(Population) FROM POPULATION1;

-- WHICH IS ODD AND WHICH IS EVEN INTERNET_RATE?
SELECT 
  Country,
  INTERNET_USER, 
  CASE 
  WHEN INTERNET_USER % 2 == 0 THEN "EVEN"
  ELSE "ODD" 
  END AS CONDITION 
FROM POPULATION1;

SELECT 
  Country, 
  INTERNET_USER, 
  CASE WHEN INTERNET_USER % 2 == 0 THEN "EVEN" 
  ELSE "ODD" 
  END AS CONDITION 
  FROM POPULATION1 
GROUP BY(CONDITION);