CREATE TABLE DEPARTMENT(
  ID TEXT,
  NAME TEXT,
  DEP_ID TEXT,
  SALARY REAL
);

INSERT INTO DEPARTMENT (ID, NAME, DEP_ID, SALARY) VALUES 
('E001', 'Alice Johnson', 'HR', 55000.00),
('E002', 'Bob Smith', 'IT', 70000.00),
('E003', 'Charlie Davis', 'FIN', 65000.00),
('E004', 'Diana Roberts', 'IT', 72000.00),
('E005', 'Evan Lee', 'HR', 50000.00),
('E006', 'Fiona Chen', 'MKT', 58000.00),
('E007', 'George Hall', 'FIN', 63000.00),
('E008', 'Hannah Scott', 'MKT', 60000.00),
('E009', 'Ian Wright', 'IT', 75000.00),
('E010', 'Jenny Kim', 'HR', 52000.00);

-- COUNT THE NUMBER OF EMPLOYEES?
SELECT DEP_ID AS "DEPERTMENT CODE",
COUNT(*) AS "NUMBER OF EMPLOYEES"
FROM DEPARTMENT
GROUP BY DEP_ID;

-- WHAT IS THE SUM OF THE SALARY OF EACH DEPARTMENT?
SELECT DEP_ID, SUM(SALARY)
FROM DEPARTMENT
GROUP BY DEP_ID;

-- COUNT THE NUMBER OF EMPLOYEEs and sum of SALARY OF EAACH DEPARTMENT
SELECT DEP_ID AS "DEPARTMENT CODE",
COUNT(*) AS "NUMBER OFEMPLOYEES",
SUM(SALARY) AS "TOTAL SALARY"
FROM DEPARTMENT
GROUP BY DEP_ID; 

-- sum the salary of specific desprtment
SELECT DEP_ID AS "DEPARTMENT CODE",
SUM(SALARY) AS "TOTAL SALARY"
FROM DEPARTMENT
WHERE DEP_ID = 'HR';

-- FIND WHICH COLUMNS HAS MORE THAN TWO EMPLOYEES?
SELECT DEP_ID, COUNT(*) AS "NUMBER OF EMPLOYEES"
FROM DEPARTMENT
GROUP BY DEP_ID
HAVING COUNT(*) > 2;