CREATE TABLE PRODUCT1(
  ID TEXT PRIMARY KEY,
  NAME TEXT,
  PRICE TEXT,
  COM TEXT
);

INSERT INTO PRODUCT1(ID, NAME, PRICE, COM) VALUES
("101","MOTHER BOARD","3200","15"),
("102","KEY BOARD","450","16"),
("103","ZIP DRIVE","250","14"),
("104","SPEAKER","550","16"),
("105","MONITOR","5000","11"),
("106","DVD DRIVE","900","12"),
("107","CD DRIVE","800","12"),
("108","PRINTER","2600","13"),
("109","REFILL CARTRIDGE","350","13"),
("110","MOUSE","250","12");

SELECT * FROM PRODUCT1;

-- WHICH VALUES HAVE 2 IN SECOND POSITION?
SELECT NAME, PRICE FROM PRODUCT1 WHERE NAME LIKE '_R%';

-- WHAT IS THE MAX VALUE?
SELECT NAME, MAX(PRICE) AS MAXIMUM_PRICE FROM PRODUCT1;

-- WHICH IS TH MINIMUM VALUE?
SELECT NAME, MIN(PRICE) AS MAXIMUM_PRICE FROM PRODUCT1;

-- AND SYNTAX
SELECT ID, NAME, PRICE FROM PRODUCT1 WHERE NAME = "MOUSE" AND PRICE = 250;

-- OR 
SELECT ID, NAME, PRICE FROM PRODUCT1 WHERE NAME = "MOUSE" OR PRICE = 250;

-- UPDATE
UPDATE PRODUCT1 SET NAME = "MOUSE" WHERE NAME = "ZIP DRIVE";

-- OR 
SELECT ID, NAME, PRICE FROM PRODUCT1 WHERE NAME = "MOUSE" OR PRICE = 250;

-- DELETE TABLE
DELETE FROM PRODUCT1;