CREATE TABLE STUDENT1(
  ROLL_NO TEXT,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE TEXT,
  AGE INTEGER
);

-- Insert sample data into the student table
INSERT INTO STUDENT1(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('01', 'Mahdi', 'DHAKA', '********', 12),
('02', 'Hasan', 'DHAKA', '********', 18),
('03', '12345', 'DHAKA', '********', 19),
('04', 'Nasit', 'DHAKA', '********', 20),
('05', 'Amitt', 'MUMBAI', '********', 40);

SELECT * FROM STUDENT1;

SELECT * FROM STUDENT1 WHERE AGE = 18 AND ADDRESS = 'DHAKA';

SELECT * FROM STUDENT1 WHERE AGE = 18 AND NAME = 'AMITT';

SELECT * FROM STUDENT WHERE NAME = 'MAHDI' OR NAME='HASAN';

SELECT * FROM STUDENT WHERE NAME = 'MAHDI' OR AGE='20';

SELECT * FROM STUDENT WHERE NAME = 'MAHDI' AND (NAME='HASAN' OR AGE = 14);