CREATE TABLE PRODUCTS(
 PRODUCT_ID TEXT PRIMARY KEY,
 PRODUCT_NAME TEXT, 
 SUPPLIER_ID TEXT, 
 CATEGORY_ID TEXT, 
 UNIT TEXT, 
 PRICE REAL
);

INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
('1', 'CHIS', '1', '1', '10 B', 18),
('2', 'CHANG', '1', '1', '514841 CD', 19),
('3', 'SYRUP', '1', '2', '4041-21114 GDS', 10),
('4', 'RICE', '1', '2', '1-01 PPP', 22),
('5', 'BEEF', '2', '2', '215-11 QQQ', 21.35);

-- HOW MANY PRODUCTS ARE THERE?
SELECT COUNT(PRODUCT_ID) AS PRODUCT_COUNT FROM PRODUCTS;

-- WHAT IS THE AVERAGE PRICE?
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM PRODUCTS;

-- WHAT IS THE SUM OF PRICEES?
SELECT SUM(PRICE) AS TOTAL_PRICE FROM PRODUCTS;


-- WHAT ARE THE UNIC SUPPLIER_ID?
SELECT DISTINCT(SUPPLIER_ID) AS UNIC_SUPPLIER_ID FROM PRODUCTS;

-- HOW MANY UNIC SUPPLIER ID ARE THERE?
SELECT COUNT(DISTINCT(SUPPLIER_ID)) AS HOW_MANY_UNIC_SUPPLIER_ID_ARE_THERE  FROM PRODUCTS;

-- WHAT ARE THE MINIMUM AND MAXIMUM PRICES?
SELECT MIN(PRICE) AS MINIMUM_PRICE FROM PRODUCTS;

SELECT MAX(PRICE) AS MINIMUM_PRICE FROM PRODUCTS;

-- ALL WHERE SQL-AGRREGATE FUNCTIONS